print("1. Mix 500g of Flour, 10g of Yeast and 300ml of Water ina bowl.")
print("2. kneed the dough for 10 minutes.")
print("3. add 3g of salt.")
print("4. Leave to rise for 2 hours.")
print("5. bake at 200 degrees for 30 minutes.")
